use_real_data: false #true - używa danych realnych, false - używa danych syntetycznych.

enabled_algorithsm:
    support_vector_machines: true
    one_vs_one: false
    one_vs_rest: false
    random_forest: true

show_plots: false