# Plik konfiguracyjny.

use_real_data: false # true - używa danych realnych, false - używa danych syntetycznych,
alpha: 0.05 # do testu T studenta.

enabled_algorithsm:
    support_vector_machines: true
    one_vs_one: true
    one_vs_rest: true
    random_forest: true
